version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: false
    volumes:
      - .:/var/www
      - /var/www/storage
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:13  # Yangi va barqaror versiyani belgilash
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: nt_rentapp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "81:80"
    networks:
      - app-network

  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  node:
    image: node:20
    container_name: node
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    command: bash -c "npm install && npm run build"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
